services:
  - type: web
    name: monitoringmedi-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://USER:PASSWORD@HOST:PORT/DATABASE?pgbouncer=true
      - key: DIRECT_URL
        value: postgresql://USER:PASSWORD@HOST:PORT/DATABASE
    plan: free
